name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    container: google/cloud-sdk

    steps:
      - uses: actions/checkout@v1

      - name: Install Libraries and Dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_10.x | bash -
          apt-get install -y google-cloud-sdk-firestore-emulator nodejs
          npm install

      - name: Run tests
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
        run: ./node_modules/.bin/concurrently -k --success first "npm run start:functions || true" "npm run start:firestore || true" "npm run test"


  Deploy:
    runs-on: ubuntu-latest
    container: google/cloud-sdk:alpine
    needs: Test

    steps:
      - uses: actions/checkout@v1

      - name: Init Gcloud CLI
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo ${GCLOUD_SERVICE_KEY} > ./keyfile.json
          gcloud auth activate-service-account --key-file ./keyfile.json

      - name: Deploy Cloud Functions
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
        run: |
          gcloud functions deploy trigger --project ifttt-gates --runtime nodejs10 --entry-point trigger --trigger-http --allow-unauthenticated --set-env-vars AUTH_KEY=$AUTH_KEY
          gcloud functions deploy update --project ifttt-gates --runtime nodejs10 --entry-point update --trigger-http --allow-unauthenticated --set-env-vars AUTH_KEY=$AUTH_KEY
